Traceback (most recent call last):
  File "/root/Apps/ashen_boring/github.py", line 3, in <module>
    from flask_apscheduler import APScheduler
ModuleNotFoundError: No module named 'flask_apscheduler'
Traceback (most recent call last):
  File "github.py", line 1, in <module>
    from flask import Flask, render_template, jsonify
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "github.py", line 1, in <module>
    from flask import Flask, render_template, jsonify
ModuleNotFoundError: No module named 'flask'
 * Serving Flask app 'github'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8801
 * Running on http://172.26.23.117:8801
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 596-734-328
1.202.165.115 - - [25/Jun/2023 16:28:07] "GET / HTTP/1.1" 200 -
1.202.165.115 - - [25/Jun/2023 16:28:10] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
47.92.67.105 - - [25/Jun/2023 17:49:57] "GET http://39.100.66.203:8801/ HTTP/1.1" 200 -
8.142.87.162 - - [25/Jun/2023 17:49:57] "GET http://39.100.66.203/ HTTP/1.1" 200 -
47.92.72.15 - - [25/Jun/2023 17:49:57] "[33mGET http://39.100.66.203/favicon.ico HTTP/1.1[0m" 404 -
89.248.165.71 - - [25/Jun/2023 18:30:55] code 400, message Bad request syntax ('\x03\x00\x00\x13\x0eà\x00\x00\x00\x00\x00\x01\x00\x08\x00\x02\x00\x00\x00')
89.248.165.71 - - [25/Jun/2023 18:30:55] "[35m[1m\x03\x00\x00\x13\x0eà\x00\x00\x00\x00\x00\x01\x00\x08\x00\x02\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
87.236.176.66 - - [25/Jun/2023 19:12:49] "GET / HTTP/1.1" 200 -
39.103.164.38 - - [25/Jun/2023 19:48:49] "GET / HTTP/1.0" 200 -
39.103.164.38 - - [25/Jun/2023 19:48:52] "OPTIONS / HTTP/1.0" 200 -
39.103.164.38 - - [25/Jun/2023 19:48:58] code 400, message Bad request version ('RTSP/1.0')
39.103.164.38 - - [25/Jun/2023 19:48:58] "[35m[1mOPTIONS / RTSP/1.0[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:09] code 400, message Bad request version ('\x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:49:09] "[35m[1m\x80\x00\x00(rþ\x1d\x13\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x86 \x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:16] code 400, message Bad HTTP/0.9 request type ('\x00')
39.103.164.38 - - [25/Jun/2023 19:49:16] "[35m[1m\x00\x1e\x00\x06\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x07version\x04bind\x00\x00\x10\x00\x03[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:22] code 400, message Bad HTTP/0.9 request type ('\x00')
39.103.164.38 - - [25/Jun/2023 19:49:22] "[35m[1m\x00\x0c\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:24] code 400, message Bad request syntax ('EHLO')
39.103.164.38 - - [25/Jun/2023 19:49:24] "[35m[1mEHLO[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:27] code 400, message Bad request syntax ('HELP')
39.103.164.38 - - [25/Jun/2023 19:49:27] "[35m[1mHELP[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:31] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00')
39.103.164.38 - - [25/Jun/2023 19:49:31] "[35m[1m\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:35] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00*%à\x00\x00\x00\x00\x00Cookie:')
39.103.164.38 - - [25/Jun/2023 19:49:35] "[35m[1m\x03\x00\x00*%à\x00\x00\x00\x00\x00Cookie: mstshash=nmap[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:39] code 400, message Bad request version ('\x00/\x00')
39.103.164.38 - - [25/Jun/2023 19:49:39] "[35m[1m\x16\x03\x00\x00i\x01\x00\x00e\x03\x03U\x1c§ärandom1random2random3random4\x00\x00\x0c\x00/\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:44] code 400, message Bad HTTP/0.9 request type ('\x80\x9e\x01\x03\x01\x00u\x00\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:49:44] "[35m[1m\x80\x9e\x01\x03\x01\x00u\x00\x00\x00 \x00\x00f\x00\x00e\x00\x00d\x00\x00c\x00\x00b\x00\x00:\x00\x009\x00\x008\x00\x005\x00\x004\x00\x003\x00\x002\x00\x00/\x00\x00\x1b\x00\x00\x1a\x00\x00\x19\x00\x00\x18\x00\x00\x17\x00\x00\x16\x00\x00\x15\x00\x00\x14\x00\x00\x13\x00\x00\x12\x00\x00\x11\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:48] code 400, message Bad request syntax ('\x00\x00\x00qj\x81n0\x81k¡\x03\x02\x01\x05¢\x03\x02\x01')
39.103.164.38 - - [25/Jun/2023 19:49:48] "[35m[1m\x00\x00\x00qj\x81n0\x81k¡\x03\x02\x01\x05¢\x03\x02\x01[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:49:58] code 400, message Bad request version ('0.12\x00')
39.103.164.38 - - [25/Jun/2023 19:49:58] "[35m[1m\x00\x00\x00¤ÿSMBr\x00\x00\x00\x00\x08\x01@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x06\x00\x00\x01\x00\x00\x81\x00\x02PC NETWORK PROGRAM 1.0\x00\x02MICROSOFT NETWORKS 1.03\x00\x02MICROSOFT NETWORKS 3.0\x00\x02LANMAN1.0\x00\x02LM1.2X002\x00\x02Samba\x00\x02NT LANMAN 1.0\x00\x02NT LM 0.12\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:50:06] code 400, message Bad HTTP/0.9 request type ('l\x00')
39.103.164.38 - - [25/Jun/2023 19:50:06] "[35m[1ml\x00\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:50:07] "[33mGET /nice%20ports,/Trinity.txt.bak HTTP/1.0[0m" 404 -
39.103.164.38 - - [25/Jun/2023 19:50:12] code 400, message Bad request syntax ('\x01default')
39.103.164.38 - - [25/Jun/2023 19:50:12] "[35m[1m\x01default[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:50:16] code 400, message Bad request syntax ('0\x84\x00\x00\x00-\x02\x01\x07c\x84\x00\x00\x00$\x04\x00')
39.103.164.38 - - [25/Jun/2023 19:50:16] "[35m[1m0\x84\x00\x00\x00-\x02\x01\x07c\x84\x00\x00\x00$\x04\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:50:25] code 400, message Bad HTTP/0.9 request type ('0')
39.103.164.38 - - [25/Jun/2023 19:50:25] "[35m[1m0\x0c\x02\x01\x01`\x07\x02\x01\x02\x04\x00\x80\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:50:25] code 400, message Bad request version ('SIP/2.0')
39.103.164.38 - - [25/Jun/2023 19:50:25] "[35m[1mOPTIONS sip:nm SIP/2.0[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:50:35] code 400, message Bad request syntax ('TNMP\x04\x00\x00\x00TNME\x00\x00\x04\x00')
39.103.164.38 - - [25/Jun/2023 19:50:35] "[35m[1mTNMP\x04\x00\x00\x00TNME\x00\x00\x04\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:50:42] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:50:42] "[35m[1m\x03\x00\x00\x0b\x06à\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:50:48] code 400, message Bad request syntax ('DmdT\x00\x00\x00\x17\x00\x00\x00\x01\x00\x00\x00\x00\x11\x11\x00ÿ\x01ÿ\x13')
39.103.164.38 - - [25/Jun/2023 19:50:48] "[35m[1mDmdT\x00\x00\x00\x17\x00\x00\x00\x01\x00\x00\x00\x00\x11\x11\x00ÿ\x01ÿ\x13[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:50:54] code 400, message Bad HTTP/0.9 request type (':\x00\x00\x00/\x00\x00\x00\x02\x00\x00@\x02\x0f\x00\x01\x00=\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/\x00\x00\x00\x00\x00\x00\x00\x00\x00@')
39.103.164.38 - - [25/Jun/2023 19:50:54] "[35m[1m:\x00\x00\x00/\x00\x00\x00\x02\x00\x00@\x02\x0f\x00\x01\x00=\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x1f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:00] code 400, message Bad request syntax ('DIST00000001ARGC00000005ARGV00000002ccARGV00000002-cARGV00000006nmap.cARGV00000002-oARGV00000006nmap.oDOTI00000000')
39.103.164.38 - - [25/Jun/2023 19:51:00] "[35m[1mDIST00000001ARGC00000005ARGV00000002ccARGV00000002-cARGV00000006nmap.cARGV00000002-oARGV00000006nmap.oDOTI00000000[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:05] code 400, message Bad request syntax ('JRMI\x00\x02K')
39.103.164.38 - - [25/Jun/2023 19:51:05] "[35m[1mJRMI\x00\x02K[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:11] code 400, message Bad request syntax ('\x01\x00\x00\x00\x01\x00\x00\x00\x08\x08')
39.103.164.38 - - [25/Jun/2023 19:51:11] "[35m[1m\x01\x00\x00\x00\x01\x00\x00\x00\x08\x08[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:12] code 400, message Bad request version ('>')
39.103.164.38 - - [25/Jun/2023 19:51:12] "[35m[1m< NTP/1.0 >[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:18] code 400, message Bad request version ('\x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00àmß_')
39.103.164.38 - - [25/Jun/2023 19:51:18] "[35m[1m\x01\x00\x00ýÎú\x0b° \x00\x00\x00MMS\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x01\x00\x03\x00ðððð\x0b\x00\x04\x00\x1c\x00\x03\x00N\x00S\x00P\x00l\x00a\x00y\x00e\x00r\x00/\x009\x00.\x000\x00.\x000\x00.\x002\x009\x008\x000\x00;\x00 \x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00àmß_[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:24] code 400, message Bad HTTP/0.9 request type ('\x00Z\x00\x00\x01\x00\x00\x00\x016\x01,\x00\x00\x08\x00\x7fÿ\x7f\x08\x00\x00\x00\x01\x00')
39.103.164.38 - - [25/Jun/2023 19:51:24] "[35m[1m\x00Z\x00\x00\x01\x00\x00\x00\x016\x01,\x00\x00\x08\x00\x7fÿ\x7f\x08\x00\x00\x00\x01\x00 \x00:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x004æ\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00(CONNECT_DATA=(COMMAND=version))[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:25] code 400, message Bad request syntax ('Subscribe')
39.103.164.38 - - [25/Jun/2023 19:51:25] "[35m[1mSubscribe[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:27] code 400, message Bad request syntax ('Query')
39.103.164.38 - - [25/Jun/2023 19:51:27] "[35m[1mQuery[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:29] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
39.103.164.38 - - [25/Jun/2023 19:51:29] "[35m[1m\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:37] code 400, message Bad request syntax ('\x04\x01\x00\x16\x7f\x00\x00\x01root\x00')
39.103.164.38 - - [25/Jun/2023 19:51:37] "[35m[1m\x04\x01\x00\x16\x7f\x00\x00\x01root\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:43] code 400, message Bad request version ('\x03\x00(\x00\x04ÿ\x08\x00\x01U\x00\x00\x00MSSQLServer\x00H\x0f\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:51:43] "[35m[1m\x12\x01\x004\x00\x00\x00\x00\x00\x00\x15\x00\x06\x01\x00\x1b\x00\x01\x02\x00\x1c\x00\x0c\x03\x00(\x00\x04ÿ\x08\x00\x01U\x00\x00\x00MSSQLServer\x00H\x0f\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:44] code 400, message Bad request syntax ('HELP')
39.103.164.38 - - [25/Jun/2023 19:51:44] "[35m[1mHELP[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:46] code 400, message Bad request syntax ('stats')
39.103.164.38 - - [25/Jun/2023 19:51:46] "[35m[1mstats[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:47] code 400, message Bad request version ('\x06\x00\x00\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:51:47] "[35m[1m\x00\x00\x00\x01\x00\x00\x00\x13\x00\x00\x00\x02\x00\x00\x00$\x00\x00\x00\x0bservice_mgr\x00\x00\x00\x00\x02\x00\x00\x00\x13\x01\x08scanner \x04\x05nmap \x06\x00\x00\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:51:55] code 400, message Bad request version ('\x00\x00\x00\x04')
39.103.164.38 - - [25/Jun/2023 19:51:55] "[35m[1m\x00\x00\x00\x00DB2DAS      \x01\x04\x00\x00\x00\x109z\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x0c\x00\x00\x00\x00\x00\x00\x0c\x00\x00\x00\x0c\x00\x00\x00\x04[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:02] code 400, message Bad request version ('\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00ÿ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00ä\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x7f')
39.103.164.38 - - [25/Jun/2023 19:52:02] "[35m[1m\x01Â\x00\x00\x00\x04\x00\x00¶\x01\x00\x00SQLDB2RA\x00\x01\x00\x00\x04\x01\x01\x00\x05\x00\x1d\x00\x88\x00\x00\x00\x01\x00\x00\x80\x00\x00\x00\x01\x09\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x01\x09\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x01\x08\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x01\x00\x00@\x00\x00\x00@\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x02\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x00\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x80\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00\x80\x00\x00\x00\x01\x04\x00\x00\x00\x03\x00\x00\x80\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00\x80\x00\x00\x00\x01\x08\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x10\x00\x00\x00\x01\x00\x00\x80\x00\x00\x00\x01\x10\x00\x00\x00\x01\x00\x00\x80\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x09\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x01\x09\x00\x00\x00\x01\x00\x00\x80\x00\x00\x00\x01\x04\x00\x00\x00\x03\x00\x00\x80\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x04\x00\x00\x01\x00\x00\x80\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x01\x00\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x00        \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00ÿ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00ä\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x7f[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:09] code 400, message Bad request version ('1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:52:09] "[35m[1mClient string for PARC version 1 Wire Encryption version 1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:09] code 400, message Bad HTTP/0.9 request type ('<\x00K\x00\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:52:09] "[35m[1m<\x00K\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00ÿÿÿÿ\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:11] code 400, message Bad request syntax ('\x124\x00\x01')
39.103.164.38 - - [25/Jun/2023 19:52:11] "[35m[1m\x124\x00\x01[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:18] code 400, message Bad request syntax ('\x00\x03\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x0f\x00')
39.103.164.38 - - [25/Jun/2023 19:52:18] "[35m[1m\x00\x03\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x0f\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:19] code 400, message Bad request syntax ('serverstatus')
39.103.164.38 - - [25/Jun/2023 19:52:19] "[35m[1mserverstatus[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:27] code 400, message Bad HTTP/0.9 request type ('Âååå\x9e')
39.103.164.38 - - [25/Jun/2023 19:52:27] "[35m[1mÂååå\x9e ×¤¦ÐÕÝÜÈÖÝ×ÕÈÑÖ\x83\x80ÈÝ¤Ñ¡È¤ÒÕ×Ý£¤¡Ý¦×Ý\x98å[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:28] code 400, message Bad request syntax ('#ST')
39.103.164.38 - - [25/Jun/2023 19:52:28] "[35m[1m#ST[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:35] code 400, message Bad request version ('\x00\x00\x00\x03\x00\x05nmap\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j\x00\x00\x00\x7f')
39.103.164.38 - - [25/Jun/2023 19:52:35] "[35m[1m\x00\x94\x01<\x00\x00\x00d\x00e\x00\x00\x00=\x00\x06IEEEM\x00\x00lsqlexec\x00\x00\x00\x00\x00\x00\x069.280\x00\x00\x0cRDS#R000000\x00\x00\x05sqli\x00\x00\x00\x013\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x05nmap\x00\x00\x05nmap\x00ol\x00\x00\x00\x00\x00\x00\x00\x00\x00=tlitcp\x00\x00\x00\x00\x00\x01\x00h\x00\x0b\x00\x00\x00\x03\x00\x05nmap\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j\x00\x00\x00\x7f[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:41] code 400, message Bad request syntax ('\x002Ð\x01\x00\x01\x00,\x10A\x00\x04\x11^\x00\x04\x11m\x00\x04\x11Z\x00\x18\x14\x04\x14\x03\x00\x07$\x07\x00\x08$\x0f\x00\x08\x14@\x00\x08\x14t\x00\x08\x00\x04\x11G')
39.103.164.38 - - [25/Jun/2023 19:52:41] "[35m[1m\x002Ð\x01\x00\x01\x00,\x10A\x00\x04\x11^\x00\x04\x11m\x00\x04\x11Z\x00\x18\x14\x04\x14\x03\x00\x07$\x07\x00\x08$\x0f\x00\x08\x14@\x00\x08\x14t\x00\x08\x00\x04\x11G[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:42] code 400, message Bad HTTP/0.9 request type ('TSH')
39.103.164.38 - - [25/Jun/2023 19:52:42] "[35m[1mTSH \x00\x00\x00ì\x01\x011\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x11\x04¸\x00\x00ID  [0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:43] "[33mGET /server-info HTTP/1.1[0m" 404 -
39.103.164.38 - - [25/Jun/2023 19:52:49] code 400, message Bad request syntax ('A\x00\x00\x00:0\x00\x00ÿÿÿÿÔ\x07\x00\x00\x00\x00\x00\x00test.$cmd\x00\x00\x00\x00\x00ÿÿÿÿ\x1b\x00\x00\x00\x01serverStatus\x00\x00\x00\x00\x00\x00\x00ð?\x00')
39.103.164.38 - - [25/Jun/2023 19:52:49] "[35m[1mA\x00\x00\x00:0\x00\x00ÿÿÿÿÔ\x07\x00\x00\x00\x00\x00\x00test.$cmd\x00\x00\x00\x00\x00ÿÿÿÿ\x1b\x00\x00\x00\x01serverStatus\x00\x00\x00\x00\x00\x00\x00ð?\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:50] code 400, message Bad request syntax ('*1')
39.103.164.38 - - [25/Jun/2023 19:52:50] "[35m[1m*1[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:58] code 400, message Bad request syntax ('\x00\x00\x00\x01\x07')
39.103.164.38 - - [25/Jun/2023 19:52:58] "[35m[1m\x00\x00\x00\x01\x07[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:52:59] code 400, message Bad HTTP/0.9 request type ('show')
39.103.164.38 - - [25/Jun/2023 19:52:59] "[35m[1mshow info[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:53:07] code 400, message Bad request syntax ('\x80\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x15ðÑb\x00\x00\x00\x00\x00\x00\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:53:07] "[35m[1m\x80\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x15ðÑb\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:53:13] code 400, message Bad request syntax ('\x00\x01n')
39.103.164.38 - - [25/Jun/2023 19:53:13] "[35m[1m\x00\x01n[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:53:18] code 400, message Bad request syntax ('vp3')
39.103.164.38 - - [25/Jun/2023 19:53:18] "[35m[1mvp3[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:53:24] code 400, message Bad request syntax ('\x94\x00ÍïÑa\x91\x03')
39.103.164.38 - - [25/Jun/2023 19:53:24] "[35m[1m\x94\x00ÍïÑa\x91\x03[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:53:30] code 400, message Bad request syntax ('þ\x01')
39.103.164.38 - - [25/Jun/2023 19:53:30] "[35m[1mþ\x01[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:53:31] "[33mGET /version HTTP/1.1[0m" 404 -
39.103.164.38 - - [25/Jun/2023 19:53:38] code 400, message Bad request syntax ('\x00\x00\x07\x00\x08\x00\x03\x00\x04\x00\x05\x00\x06')
39.103.164.38 - - [25/Jun/2023 19:53:38] "[35m[1m\x00\x00\x07\x00\x08\x00\x03\x00\x04\x00\x05\x00\x06[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:53:44] code 400, message Bad request syntax ('ÿû\x18ÿú\x18\x00IBM-3279-4-Eÿðÿû\x19ÿý\x19ÿû\x00ÿý\x00')
39.103.164.38 - - [25/Jun/2023 19:53:44] "[35m[1mÿû\x18ÿú\x18\x00IBM-3279-4-Eÿðÿû\x19ÿý\x19ÿû\x00ÿý\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:53:50] code 400, message Bad request syntax ('GIOP\x01\x00\x01\x00$\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00abcdef\x00\x00\x04\x00\x00\x00get\x00\x00\x00\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:53:50] "[35m[1mGIOP\x01\x00\x01\x00$\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00abcdef\x00\x00\x04\x00\x00\x00get\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:53:55] code 400, message Bad request syntax ('VERSION')
39.103.164.38 - - [25/Jun/2023 19:53:55] "[35m[1mVERSION[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:54:00] code 400, message Bad request syntax ('CNXN\x00\x00\x00\x01\x00\x10\x00\x00\x07\x00\x00\x002\x02\x00\x00¼±§±host::\x00')
39.103.164.38 - - [25/Jun/2023 19:54:00] "[35m[1mCNXN\x00\x00\x00\x01\x00\x10\x00\x00\x07\x00\x00\x002\x02\x00\x00¼±§±host::\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:54:05] code 400, message Bad HTTP/0.9 request type ('\x00\x00\x00\x10\x00\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:54:05] "[35m[1m\x00\x00\x00\x10\x00\x00\x00\x0c{"code":106}[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:54:10] code 400, message Bad request syntax ('\x0c\x00\x01\x00\x00\x00ImYorDad0u\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:54:10] "[35m[1m\x0c\x00\x01\x00\x00\x00ImYorDad0u\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:54:16] code 400, message Bad HTTP/0.9 request type ('ÚÚ\x01\x00\x00\x00\x14\x00\x10\x03\x08\x00\x00\x00')
39.103.164.38 - - [25/Jun/2023 19:54:16] "[35m[1mÚÚ\x01\x00\x00\x00\x14\x00\x10\x03\x08\x00\x00\x00\x0bM\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:56:09] code 400, message Bad request version ("UR\x9b¹Æ2rTÎ¿îÀÃ\x839\x00\x9c\x13\x02\x13\x03\x13\x01\x003\x009\x005\x00/À,À0\x00£\x00\x9fÌ©Ì¨ÌªÀ¯À\xadÀ£À\x9fÀ]ÀaÀWÀSÀ+À/\x00¢\x00\x9eÀ®À¬À¢À\x9eÀ\\À`ÀVÀRÀ$À(\x00k\x00jÀsÀw\x00Ä\x00ÃÀ#À'\x00g\x00@ÀrÀv\x00¾\x00½À")
39.103.164.38 - - [25/Jun/2023 19:56:09] "[35m[1m\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03ÌVK`\x9dýÂ} j\x8ebQ)þ}YÔ¬³&­Ü÷\x97\x8d0\x96\x0fè;\x0f \x01\x88éI\x95\x1d½\x8b\x93Þê\x16aS'¨\x0dUR\x9b¹Æ2rTÎ¿îÀÃ\x839\x00\x9c\x13\x02\x13\x03\x13\x01\x003\x009\x005\x00/À,À0\x00£\x00\x9fÌ©Ì¨ÌªÀ¯À­À£À\x9fÀ]ÀaÀWÀSÀ+À/\x00¢\x00\x9eÀ®À¬À¢À\x9eÀ\\À`ÀVÀRÀ$À(\x00k\x00jÀsÀw\x00Ä\x00ÃÀ#À'\x00g\x00@ÀrÀv\x00¾\x00½À[0m" HTTPStatus.BAD_REQUEST -
39.103.164.38 - - [25/Jun/2023 19:56:30] code 400, message Bad HTTP/0.9 request type ('\x80\x00\x00()búª\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x86')
39.103.164.38 - - [25/Jun/2023 19:56:30] "[35m[1m\x80\x00\x00()búª\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x86 \x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
87.236.176.251 - - [25/Jun/2023 19:57:23] "GET / HTTP/1.1" 200 -
162.216.149.133 - - [25/Jun/2023 20:12:09] "GET / HTTP/1.1" 200 -
47.92.78.77 - - [25/Jun/2023 20:41:34] "GET http://iostools.site:8801/ HTTP/1.1" 200 -
47.92.79.156 - - [25/Jun/2023 20:41:34] "GET http://iostools.site/ HTTP/1.1" 200 -
47.92.79.86 - - [25/Jun/2023 20:41:34] "[33mGET http://iostools.site/favicon.ico HTTP/1.1[0m" 404 -
To github.com:ashen-23/ashen_boring.git
   d179ffc..32bbaa9  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-26 02:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   32bbaa9..0e1782f  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-26 02:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
47.92.29.136 - - [25/Jun/2023 21:44:16] "GET http://39.100.66.203:8801/ HTTP/1.1" 200 -
47.92.36.178 - - [25/Jun/2023 21:44:16] "GET http://39.100.66.203/ HTTP/1.1" 200 -
47.92.36.178 - - [25/Jun/2023 21:44:16] "[33mGET http://39.100.66.203/favicon.ico HTTP/1.1[0m" 404 -
47.92.73.109 - - [25/Jun/2023 21:52:53] "GET http://i.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.36.178 - - [25/Jun/2023 21:52:53] "GET http://i.ashen23.site/ HTTP/1.1" 200 -
47.92.32.64 - - [25/Jun/2023 21:52:53] "[33mGET http://i.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
To github.com:ashen-23/ashen_boring.git
   0e1782f..76076df  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-26 07:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 76076dfd78fbdaeae8ac8ae23fc787a83e4361e1 but expected 0e1782fcf592ecf0d6c8a499e92a28dfb960e194)
错误：无法推送一些引用到 'github.com:ashen-23/ashen_boring.git'
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-26 07:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
87.236.176.12 - - [26/Jun/2023 02:44:29] "GET / HTTP/1.1" 200 -
39.103.159.236 - - [26/Jun/2023 03:04:15] code 400, message Bad request version ("Í\x15¿ÆüÙ³^\xadïþ\x8bTª\x12ÊëõºÄ\x1a3U>Fsõ6x9bI\x00>\x13\x02\x13\x03\x13\x01À,À0\x00\x9fÌ©Ì¨ÌªÀ+À/\x00\x9eÀ$À(\x00kÀ#À'\x00gÀ")
39.103.159.236 - - [26/Jun/2023 03:04:15] "[35m[1m\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03sÀ·^mE°\x1c¥ b³eñi\x17Øò8{âR)@\x95e\x15l äåÈ Í\x15¿ÆüÙ³^­ïþ\x8bTª\x12ÊëõºÄ\x1a3U>Fsõ6x9bI\x00>\x13\x02\x13\x03\x13\x01À,À0\x00\x9fÌ©Ì¨ÌªÀ+À/\x00\x9eÀ$À(\x00kÀ#À'\x00gÀ[0m" HTTPStatus.BAD_REQUEST -
39.103.159.236 - - [26/Jun/2023 03:04:15] "GET / HTTP/1.1" 200 -
101.133.140.205 - - [26/Jun/2023 03:07:38] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03¶gûâî')
101.133.140.205 - - [26/Jun/2023 03:07:38] "[35m[1m\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03¶gûâî[0m" HTTPStatus.BAD_REQUEST -
101.133.140.205 - - [26/Jun/2023 03:07:38] "GET / HTTP/1.1" 200 -
47.92.70.66 - - [26/Jun/2023 03:53:33] "GET http://www.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.71.160 - - [26/Jun/2023 03:53:34] "GET http://www.ashen23.site/ HTTP/1.1" 200 -
8.142.87.162 - - [26/Jun/2023 03:53:34] "[33mGET http://www.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
162.216.149.187 - - [26/Jun/2023 06:03:39] "GET / HTTP/1.1" 200 -
To github.com:ashen-23/ashen_boring.git
   76076df..a59140e  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-26 12:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   a59140e..76578cb  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-26 12:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
89.248.165.249 - - [26/Jun/2023 11:48:37] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
89.248.165.249 - - [26/Jun/2023 11:48:37] "[35m[1m\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
To github.com:ashen-23/ashen_boring.git
   76578cb..fbfbb99  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-26 17:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   fbfbb99..684268e  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-26 17:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
87.236.176.43 - - [26/Jun/2023 16:56:53] "GET / HTTP/1.1" 200 -
To github.com:ashen-23/ashen_boring.git
   684268e..e796630  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-26 22:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   e796630..4dac7ca  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-26 22:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   4dac7ca..47332c9  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-27 03:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   47332c9..ee07793  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-27 03:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
87.236.176.18 - - [26/Jun/2023 22:41:13] "GET / HTTP/1.1" 200 -
8.142.104.65 - - [26/Jun/2023 23:44:34] "GET http://ashen23.site:8801/ HTTP/1.1" 200 -
47.92.37.1 - - [26/Jun/2023 23:44:35] "GET http://ashen23.site/ HTTP/1.1" 200 -
47.92.78.126 - - [26/Jun/2023 23:44:35] "[33mGET http://ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
172.104.11.46 - - [27/Jun/2023 00:49:10] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00')
172.104.11.46 - - [27/Jun/2023 00:49:10] "[35m[1m\x16\x03\x01\x00\x85\x01\x00\x00\x81\x03\x03\x9a\x1aÛï[0m" HTTPStatus.BAD_REQUEST -
172.104.210.105 - - [27/Jun/2023 01:02:26] "GET / HTTP/1.1" 200 -
192.155.90.118 - - [27/Jun/2023 03:18:12] "GET / HTTP/1.1" 200 -
To github.com:ashen-23/ashen_boring.git
   ee07793..41ae212  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-27 08:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 41ae212371f2a656ca1220eb008ba24c1bc8fbd4 but expected ee0779300b4b68ac9b61a7122a65c145bc8fc816)
错误：无法推送一些引用到 'github.com:ashen-23/ashen_boring.git'
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-27 08:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   41ae212..a467d32  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-27 13:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at a467d323537ee7ec005253b54668eb7b658abb89 but expected 41ae212371f2a656ca1220eb008ba24c1bc8fbd4)
错误：无法推送一些引用到 'github.com:ashen-23/ashen_boring.git'
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-27 13:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
87.236.176.242 - - [27/Jun/2023 10:28:31] "GET / HTTP/1.1" 200 -
162.216.150.189 - - [27/Jun/2023 11:27:50] "GET / HTTP/1.1" 200 -
47.92.5.239 - - [27/Jun/2023 12:39:56] "GET http://tool.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.73.218 - - [27/Jun/2023 12:39:56] "GET http://tool.ashen23.site/ HTTP/1.1" 200 -
47.92.37.1 - - [27/Jun/2023 12:39:56] "[33mGET http://tool.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
To github.com:ashen-23/ashen_boring.git
   a467d32..98f3e77  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-27 18:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   98f3e77..1ba568c  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-27 18:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   1ba568c..a673705  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-27 23:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   a673705..54bca58  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-27 23:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   54bca58..cb66d6e  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-28 04:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   cb66d6e..b664b76  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-28 04:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
87.236.176.237 - - [28/Jun/2023 00:25:38] "GET / HTTP/1.1" 200 -
47.92.78.77 - - [28/Jun/2023 01:54:49] "GET http://api.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.30.57 - - [28/Jun/2023 01:54:49] "GET http://api.ashen23.site/ HTTP/1.1" 200 -
47.92.37.1 - - [28/Jun/2023 01:54:49] "[33mGET http://api.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
To github.com:ashen-23/ashen_boring.git
   b664b76..3a9a8d9  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-28 09:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 3a9a8d9dd20c40e1096a7dff09a9f0a2463f4fb5 but expected b664b7649aa5bba4915deda6eb5dae5d7642c87c)
错误：无法推送一些引用到 'github.com:ashen-23/ashen_boring.git'
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-28 09:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
89.248.165.71 - - [28/Jun/2023 05:46:12] code 400, message Bad request syntax ('\x03\x00\x00\x13\x0eà\x00\x00\x00\x00\x00\x01\x00\x08\x00\x02\x00\x00\x00')
89.248.165.71 - - [28/Jun/2023 05:46:12] "[35m[1m\x03\x00\x00\x13\x0eà\x00\x00\x00\x00\x00\x01\x00\x08\x00\x02\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
35.203.211.175 - - [28/Jun/2023 07:54:40] "GET / HTTP/1.1" 200 -
47.92.79.156 - - [28/Jun/2023 08:25:29] code 400, message Bad request syntax ("\x16\x03\x03\x01\x02\x01\x00\x00þ\x03\x03lpV\xad\x9c'\x92\x8e&v\x93kÑ¬-3ô>\x98\x054_\x0fJ½\x03ì-r\x17pÏ\x00\x00VÀ,À+À0À/\x00\x9f\x00£\x00\x9e\x00¢À$À(À#À'\x00k\x00j\x00g\x00@À.À2À-À1À&À*À%À)À")
47.92.79.156 - - [28/Jun/2023 08:25:29] "[35m[1m\x16\x03\x03\x01\x02\x01\x00\x00þ\x03\x03lpV­\x9c'\x92\x8e&v\x93kÑ¬-3ô>\x98\x054_\x0fJ½\x03ì-r\x17pÏ\x00\x00VÀ,À+À0À/\x00\x9f\x00£\x00\x9e\x00¢À$À(À#À'\x00k\x00j\x00g\x00@À.À2À-À1À&À*À%À)À[0m" HTTPStatus.BAD_REQUEST -
47.92.30.57 - - [28/Jun/2023 09:07:56] code 400, message Bad request version ("£~©Û\x00g&ï®\x00\x00VÀ,À+À0À/\x00\x9f\x00£\x00\x9e\x00¢À$À(À#À'\x00k\x00j\x00g\x00@À.À2À-À1À&À*À%À)À")
47.92.30.57 - - [28/Jun/2023 09:07:56] "[35m[1m\x16\x03\x03\x01\x02\x01\x00\x00þ\x03\x03ÜâÎ\x1c\x85NÅ Ñ3Hâbà×\x00\x8d\x92\x9a\x1caä\x1f£~©Û\x00g&ï®\x00\x00VÀ,À+À0À/\x00\x9f\x00£\x00\x9e\x00¢À$À(À#À'\x00k\x00j\x00g\x00@À.À2À-À1À&À*À%À)À[0m" HTTPStatus.BAD_REQUEST -
To github.com:ashen-23/ashen_boring.git
   3a9a8d9..1a0cbe9  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-28 14:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   1a0cbe9..a069024  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-28 14:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   a069024..7a8c872  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-28 19:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   7a8c872..ffcad62  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-28 19:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   ffcad62..36dd4f8  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-29 00:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
To github.com:ashen-23/ashen_boring.git
   36dd4f8..4f0e207  main -> main
Job "githubContribute (trigger: interval[5:00:00], next run at: 2023-06-29 00:27:50 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/Apps/ashen_boring/github.py", line 25, in githubContribute
    return jsonify({"code": 0})
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
111.7.96.149 - - [28/Jun/2023 21:52:41] code 400, message Bad request version ('À\x13À')
111.7.96.149 - - [28/Jun/2023 21:52:41] "[35m[1m\x16\x03\x01\x00î\x01\x00\x00ê\x03\x03I\x06²ù¼\x99iÀYûøºe-\x83Ud]\x0e\x8d·b8´gÆÝ9dZ8f gÁ\x81i³öòË°©\x19NÖ½\x95g|püé<Z¡\x90T·é¥8'O;\x00&À+À/À,À0Ì©Ì¨À\x09À\x13À[0m" HTTPStatus.BAD_REQUEST -
111.7.96.149 - - [28/Jun/2023 21:52:51] "GET / HTTP/1.1" 200 -
89.248.163.212 - - [28/Jun/2023 22:30:17] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
89.248.163.212 - - [28/Jun/2023 22:30:17] "[35m[1m\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
47.92.31.143 - - [28/Jun/2023 22:38:03] "GET http://39.100.66.203:8801/ HTTP/1.1" 200 -
47.92.72.15 - - [28/Jun/2023 22:38:03] "GET http://39.100.66.203/ HTTP/1.1" 200 -
47.92.30.214 - - [28/Jun/2023 22:38:03] "[33mGET http://39.100.66.203/favicon.ico HTTP/1.1[0m" 404 -
106.225.153.215 - - [28/Jun/2023 22:38:34] "GET / HTTP/1.1" 200 -
106.225.153.215 - - [28/Jun/2023 22:38:34] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
125.124.72.162 - - [28/Jun/2023 22:38:38] "GET / HTTP/1.1" 200 -
125.124.72.162 - - [28/Jun/2023 22:38:38] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
106.225.136.108 - - [28/Jun/2023 22:38:42] "GET / HTTP/1.1" 200 -
106.225.136.108 - - [28/Jun/2023 22:38:42] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
117.41.162.89 - - [28/Jun/2023 22:38:52] "GET / HTTP/1.1" 200 -
117.41.162.89 - - [28/Jun/2023 22:38:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
117.41.162.89 - - [28/Jun/2023 22:38:54] "GET / HTTP/1.1" 200 -
117.41.162.89 - - [28/Jun/2023 22:38:54] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
106.227.35.75 - - [28/Jun/2023 22:39:10] "GET / HTTP/1.1" 200 -
106.227.35.75 - - [28/Jun/2023 22:39:10] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
125.124.10.109 - - [28/Jun/2023 22:39:19] "GET / HTTP/1.1" 200 -
125.124.10.109 - - [28/Jun/2023 22:39:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
125.124.10.109 - - [28/Jun/2023 22:39:25] "GET / HTTP/1.1" 200 -
125.124.10.109 - - [28/Jun/2023 22:39:25] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
106.225.156.247 - - [28/Jun/2023 22:39:31] "GET / HTTP/1.1" 200 -
106.225.156.247 - - [28/Jun/2023 22:39:31] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
106.225.208.238 - - [28/Jun/2023 22:39:53] "GET / HTTP/1.1" 200 -
106.225.208.238 - - [28/Jun/2023 22:39:53] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
125.124.4.32 - - [28/Jun/2023 22:39:56] "GET / HTTP/1.1" 200 -
125.124.4.32 - - [28/Jun/2023 22:39:56] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
117.41.166.19 - - [28/Jun/2023 22:43:34] "GET / HTTP/1.1" 200 -
117.41.166.19 - - [28/Jun/2023 22:43:35] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
182.106.189.158 - - [28/Jun/2023 22:46:13] "GET / HTTP/1.1" 200 -
182.106.189.158 - - [28/Jun/2023 22:46:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
117.33.135.12 - - [28/Jun/2023 22:58:46] "GET / HTTP/1.1" 200 -
117.33.135.12 - - [28/Jun/2023 22:58:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
117.33.135.12 - - [28/Jun/2023 22:58:52] "GET / HTTP/1.1" 200 -
117.33.135.12 - - [28/Jun/2023 22:58:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
47.92.79.156 - - [28/Jun/2023 23:41:00] "GET http://qb.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.73.109 - - [28/Jun/2023 23:41:00] "GET http://qb.ashen23.site/ HTTP/1.1" 200 -
47.92.79.156 - - [28/Jun/2023 23:41:00] "[33mGET http://qb.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
47.92.31.143 - - [28/Jun/2023 23:41:36] "GET http://www.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.77.114 - - [28/Jun/2023 23:41:36] "GET http://www.ashen23.site/ HTTP/1.1" 200 -
8.142.42.74 - - [28/Jun/2023 23:41:36] "[33mGET http://www.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
39.103.133.249 - - [28/Jun/2023 23:41:58] "GET http://nas.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.36.178 - - [28/Jun/2023 23:42:00] "GET http://nas.ashen23.site/ HTTP/1.1" 200 -
47.92.70.66 - - [28/Jun/2023 23:42:00] "[33mGET http://nas.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
47.92.79.71 - - [28/Jun/2023 23:43:32] "GET http://docker.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.30.57 - - [28/Jun/2023 23:43:32] "GET http://docker.ashen23.site/ HTTP/1.1" 200 -
47.92.73.109 - - [28/Jun/2023 23:43:32] "[33mGET http://docker.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
47.92.30.214 - - [28/Jun/2023 23:43:53] "GET http://gelly.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.33.204 - - [28/Jun/2023 23:43:53] "GET http://gelly.ashen23.site/ HTTP/1.1" 200 -
47.92.70.66 - - [28/Jun/2023 23:43:53] "[33mGET http://gelly.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
8.142.104.65 - - [28/Jun/2023 23:44:47] "GET http://proxy.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.32.64 - - [28/Jun/2023 23:44:47] "GET http://proxy.ashen23.site/ HTTP/1.1" 200 -
47.92.37.1 - - [28/Jun/2023 23:44:47] "[33mGET http://proxy.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
47.92.31.143 - - [28/Jun/2023 23:46:06] "GET http://registry.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.68.55 - - [28/Jun/2023 23:46:07] "GET http://registry.ashen23.site/ HTTP/1.1" 200 -
47.92.79.71 - - [28/Jun/2023 23:46:07] "[33mGET http://registry.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
47.92.78.77 - - [28/Jun/2023 23:47:09] "GET http://doc.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.30.214 - - [28/Jun/2023 23:47:10] "GET http://doc.ashen23.site/ HTTP/1.1" 200 -
8.142.87.162 - - [28/Jun/2023 23:47:10] "[33mGET http://doc.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
8.142.31.72 - - [28/Jun/2023 23:48:17] "GET http://39.100.66.203:8801/ HTTP/1.1" 200 -
47.92.29.136 - - [28/Jun/2023 23:48:17] "GET http://39.100.66.203/ HTTP/1.1" 200 -
47.92.67.105 - - [28/Jun/2023 23:48:17] "[33mGET http://39.100.66.203/favicon.ico HTTP/1.1[0m" 404 -
8.142.87.162 - - [28/Jun/2023 23:48:26] "GET http://i.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.36.178 - - [28/Jun/2023 23:48:26] "GET http://i.ashen23.site/ HTTP/1.1" 200 -
47.92.37.1 - - [28/Jun/2023 23:48:26] "[33mGET http://i.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
47.92.73.218 - - [28/Jun/2023 23:49:02] "GET http://jp.ashen23.site:8801/ HTTP/1.1" 200 -
39.103.133.249 - - [28/Jun/2023 23:49:03] "GET http://jp.ashen23.site/ HTTP/1.1" 200 -
47.92.31.57 - - [28/Jun/2023 23:49:03] "[33mGET http://jp.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
47.92.32.64 - - [28/Jun/2023 23:51:25] "GET http://www.iostools.site:8801/ HTTP/1.1" 200 -
47.92.36.178 - - [28/Jun/2023 23:51:25] "GET http://www.iostools.site/ HTTP/1.1" 200 -
8.142.31.72 - - [28/Jun/2023 23:51:25] "[33mGET http://www.iostools.site/favicon.ico HTTP/1.1[0m" 404 -
47.92.37.1 - - [28/Jun/2023 23:52:02] "GET http://tool.ashen23.site:8801/ HTTP/1.1" 200 -
47.92.31.143 - - [28/Jun/2023 23:52:02] "GET http://tool.ashen23.site/ HTTP/1.1" 200 -
47.92.31.143 - - [28/Jun/2023 23:52:02] "[33mGET http://tool.ashen23.site/favicon.ico HTTP/1.1[0m" 404 -
